#!/bin/bash
cd ..
if [ "${GIT_REPO}" = "-" ]; then
  tar -C hugo -zxvf -
else
  git clone "${GIT_REPO}" hugo
  pushd hugo
    if [ "${GITHUB_PR_NUMBER}" != "-" ]; then
      git fetch origin "+refs/pull/${GITHUB_PR_NUMBER}/head:"
      git checkout -qf FETCH_HEAD
    fi
    if [ "${GIT_COMMIT}" != "-" ]; then
      git checkout -qf "${GIT_COMMIT}"
    fi
  popd
fi

cd hugo
hugo server -b http://"$(hostname)" -p "${PORT}" "${@}"
